import { Component, EventEmitter, OnDestroy, OnInit, Output, ViewChild } from '@angular/core';
import { AgGridAngular } from 'ag-grid-angular';
import { Subscription } from 'rxjs';
import { debounceTime } from 'rxjs/operators';
import { CarFilter } from 'src/app/shared-utilities/filters/car-filter/car-filter.component';
import { SharedService } from 'src/app/shared-utilities/shared.service';
import 'ag-grid-enterprise';

@Component({
  selector: 'app-customer-list',
  templateUrl: './customer-list.component.html',
  styleUrls: ['./customer-list.component.scss']
})
export class CustomerListComponent implements OnInit, OnDestroy {
  @ViewChild('agGrid') agGrid!: AgGridAngular;
  public customers: any[] = [];
  public customersData: any[]=[];
  public selectedCustomers: any;
  loading: boolean = true;
  columnDefs: any[]=[];
  pagination: boolean = true;
  paginationPageSize: number = 10;
  public frameworkComponents: any;
  public defaultColDef: any;
  public subscriptions: any = new Subscription();

  constructor(
    public sharedService: SharedService
  ) { 
    
  }

  ngOnInit(): void {
    this.customers = [
          {
              "Asset": "UTLX 642494",
              "AssetId": 93217,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Empty",
              "Origin": "HIGH LEVEL",
              "OriginState": "AB",
              "Destination": "YOUNGWOOD:ST GABRIEL:GEISMAR",
              "DestinationState": "LA",
              "LocationName": "Fort Frances",
              "LocationState": "ON",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-15T15:02:51.413",
              "Duration": "33082.11:00:00",
              "EtaDate": "2021-04-24T19:35:50.413",
              "EtaRailroadDate": "2021-04-22T13:00:00",
              "ArrivalStatus": "On Time",
              "Latitude": 48.613880157471,
              "Longitude": -93.446464538574,
              "WaybillIdentifier": "62723f4c-66b9-4c79-a9c1-a16c61341c2e",
              "WaybillDestination": "GEISMAR",
              "WaybillDestinationState": "LA",
              "TrainID": "X34241",
              "ClmCode": "P",
              "ClmSightingDate": "2021-04-15T13:05:00",
              "ClmCodeDescription": "Departure",
              "CareOfParty": "KINDER MORGAN LIQUID TERMINALS LLC",
              "RailRoad": "CN",
              "BOL": null,
              "SID": null,
              "Customer": "NORBORD INC.",
              "CustPO": null,
              "Product": "TN",
              "NetWeight": 0,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 660882",
              "AssetId": 92230,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "GEISMAR",
              "OriginState": "LA",
              "Destination": "BRIDGETON",
              "DestinationState": "MO",
              "LocationName": "Venice",
              "LocationState": "IL",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-15T13:45:10",
              "Duration": "20512.14:00:00",
              "EtaDate": "2021-04-21T07:08:07",
              "EtaRailroadDate": "2021-04-16T12:00:00",
              "ArrivalStatus": "On Time",
              "Latitude": 38.685607910156,
              "Longitude": -90.210296630859,
              "WaybillIdentifier": "72884625-eb57-4ff7-be1c-14071e5e9364",
              "WaybillDestination": "BRIDGETON",
              "WaybillDestinationState": "MO",
              "TrainID": "",
              "ClmCode": "P",
              "ClmSightingDate": "2021-04-15T13:37:00",
              "ClmCodeDescription": "Departure",
              "CareOfParty": null,
              "RailRoad": "NS",
              "BOL": 72997090,
              "SID": "2932185",
              "Customer": "RUBICON LLC",
              "CustPO": "2020-00-04092",
              "Product": "TN",
              "NetWeight": 189000,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 683686",
              "AssetId": 102803,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Empty",
              "Origin": "GEISMAR",
              "OriginState": "LA",
              "Destination": "DEVON",
              "DestinationState": "KY",
              "LocationName": "Crescent Park",
              "LocationState": "KY",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-15T10:07:04",
              "Duration": "00:00:00",
              "EtaDate": "2021-04-15T10:33:39",
              "EtaRailroadDate": "2021-04-19T23:00:00",
              "ArrivalStatus": "Late",
              "Latitude": 39.038341522217,
              "Longitude": -84.583206176758,
              "WaybillIdentifier": "d407bb4a-81de-4cf4-b075-054287b2e365",
              "WaybillDestination": "DEVON",
              "WaybillDestinationState": "KY",
              "TrainID": "",
              "ClmCode": "A",
              "ClmSightingDate": "2021-04-15T11:06:00",
              "ClmCodeDescription": "Arrival at an In - transit",
              "CareOfParty": "FIRESTONE BUILDING PRODUCTS CO",
              "RailRoad": "NS",
              "BOL": 80868474,
              "SID": "2930563",
              "Customer": "RUBICON LLC",
              "CustPO": "4570632684",
              "Product": "TN",
              "NetWeight": 188580,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 662192",
              "AssetId": 93250,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Empty",
              "Origin": "SALT LAKE CITY",
              "OriginState": "UT",
              "Destination": "YOUNGWOOD:ST GABRIEL:GEISMAR",
              "DestinationState": "LA",
              "LocationName": "El Dorado",
              "LocationState": "KS",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-15T09:24:22",
              "Duration": "17999.21:30:00",
              "EtaDate": "2021-04-20T14:57:40.5",
              "EtaRailroadDate": "2021-04-22T01:00:00",
              "ArrivalStatus": "On Time",
              "Latitude": 37.902503967285,
              "Longitude": -96.807205200195,
             "WaybillIdentifier": "07dc77c1-160c-4441-80b2-438f79c2f8d2",
              "WaybillDestination": "GEISMAR",
              "WaybillDestinationState": "LA",
              "TrainID": "",
              "ClmCode": "P",
              "ClmSightingDate": "2021-04-15T14:40:00",
              "ClmCodeDescription": "Departure",
              "CareOfParty": "RUBICON LLC",
              "RailRoad": "BNSF",
              "BOL": null,
              "SID": null,
              "Customer": "RSI LOGISTICS INC",
              "CustPO": null,
              "Product": "TN",
              "NetWeight": null,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 683707",
              "AssetId": 102852,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Empty",
              "Origin": "SALT LAKE CITY",
              "OriginState": "UT",
              "Destination": "SALT LAKE CITY",
              "DestinationState": "UT",
              "LocationName": "El Dorado",
              "LocationState": "KS",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-15T09:24:22",
              "Duration": "42122.05:00:00",
              "EtaDate": "2021-04-27T07:46:10",
              "EtaRailroadDate": "2021-04-22T01:00:00",
              "ArrivalStatus": "On Time",
              "Latitude": 37.90234375,
              "Longitude": -96.807281494141,
              "WaybillIdentifier": "0ad6143b-4a53-4954-aeff-ddd94bf4e87a",
              "WaybillDestination": "GEISMAR",
              "WaybillDestinationState": "LA",
              "TrainID": "",
              "ClmCode": "P",
              "ClmSightingDate": "2021-04-15T14:40:00",
              "ClmCodeDescription": "Departure",
              "CareOfParty": "RUBICON LLC",
              "RailRoad": "BNSF",
              "BOL": null,
              "SID": null,
              "Customer": "RSI LOGISTICS INC",
              "CustPO": null,
              "Product": "TN",
              "NetWeight": null,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 650532",
              "AssetId": 93249,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Empty",
              "Origin": "TOMAHAWK",
              "OriginState": "WI",
              "Destination": "TOMAHAWK",
              "DestinationState": "WI",
              "LocationName": "Schofield",
              "LocationState": "WI",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-15T09:20:41",
              "Duration": "00:00:00",
              "EtaDate": "2021-04-15T15:05:04",
              "EtaRailroadDate": "2021-04-24T01:00:00",
              "ArrivalStatus": "Late",
              "Latitude": 44.928134918213,
              "Longitude": -89.601112365723,
              "WaybillIdentifier": "d138c7e4-3183-40cf-9986-63c9318fdfbd",
              "WaybillDestination": "GEISMAR",
              "WaybillDestinationState": "LA",
              "TrainID": "L58881",
              "ClmCode": "P",
              "ClmSightingDate": "2021-04-15T15:00:00",
              "ClmCodeDescription": "Departure",
              "CareOfParty": null,
              "RailRoad": "CN",
              "BOL": null,
              "SID": null,
              "Customer": "LOUISIANA PACIFIC CORP",
              "CustPO": null,
              "Product": "TN",
              "NetWeight": 0,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 679797",
              "AssetId": 96806,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Empty",
              "Origin": "SALT LAKE CITY",
              "OriginState": "UT",
              "Destination": "SALT LAKE CITY",
              "DestinationState": "UT",
              "LocationName": "Provo",
              "LocationState": "UT",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-15T05:47:28",
              "Duration": "00:00:00",
              "EtaDate": "2021-04-15T15:03:35",
              "EtaRailroadDate": "2021-04-30T01:00:00",
              "ArrivalStatus": "Late",
              "Latitude": 40.223342895508,
              "Longitude": -111.651573181152,
              "WaybillIdentifier": "fef614ae-a7ce-4b45-8bdf-6901600ae60c",
              "WaybillDestination": "GEISMAR",
              "WaybillDestinationState": "LA",
              "TrainID": "RPWR31",
              "ClmCode": "A",
              "ClmSightingDate": "2021-04-15T09:28:00",
              "ClmCodeDescription": "Arrival at an In - transit",
              "CareOfParty": "RUBICON LLC",
              "RailRoad": "BNSF",
              "BOL": null,
              "SID": null,
              "Customer": "RSI LOGISTICS INC",
              "CustPO": null,
              "Product": "TN",
              "NetWeight": null,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 643069",
              "AssetId": 90370,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Empty",
              "Origin": "NEW ORLEANS",
              "OriginState": "LA",
              "Destination": "OLIVER YARD:NEW ORLEANS",
              "DestinationState": "LA",
              "LocationName": "Convent",
              "LocationState": "LA",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-15T03:04:52",
              "Duration": "111.08:00:00",
              "EtaDate": "2021-04-15T07:17:06",
              "EtaRailroadDate": "2021-04-16T13:00:00",
              "ArrivalStatus": "-",
              "Latitude": 30.07684135437,
              "Longitude": -90.886421203613,
              "WaybillIdentifier": "63ad3bac-1fef-4788-99b7-5fd653e604f6",
              "WaybillDestination": "GEISMAR",
              "WaybillDestinationState": "LA",
              "TrainID": "L51671",
              "ClmCode": "A",
              "ClmSightingDate": "2021-04-15T07:01:00",
              "ClmCodeDescription": "Arrival at an In - transit",
              "CareOfParty": "RUBICON LLC",
              "RailRoad": "CN",
              "BOL": null,
              "SID": "EMPTYMOVE",
              "Customer": "HUNTSMAN POLYURETHANES INC.",
              "CustPO": "BRAID2RUBICON",
              "Product": "TN",
              "NetWeight": 0,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 683711",
              "AssetId": 102860,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Empty",
              "Origin": "SALT LAKE CITY",
              "OriginState": "UT",
              "Destination": "YOUNGWOOD:ST GABRIEL:GEISMAR",
              "DestinationState": "LA",
              "LocationName": "Convent",
              "LocationState": "LA",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-15T03:04:46",
              "Duration": "129.06:30:00",
              "EtaDate": "2021-04-15T07:24:52.5",
              "EtaRailroadDate": "2021-04-16T13:00:00",
              "ArrivalStatus": "-",
              "Latitude": 30.079290390015,
              "Longitude": -90.88988494873,
              "WaybillIdentifier": "0fdbb982-2104-4444-b0ed-31919b3d5771",
              "WaybillDestination": "GEISMAR",
              "WaybillDestinationState": "LA",
              "TrainID": "L51671",
              "ClmCode": "A",
              "ClmSightingDate": "2021-04-15T07:01:00",
              "ClmCodeDescription": "Arrival at an In - transit",
              "CareOfParty": "RUBICON LLC",
              "RailRoad": "CN",
              "BOL": null,
              "SID": null,
              "Customer": "RSI LOGISTICS INC",
              "CustPO": null,
              "Product": "TN",
              "NetWeight": null,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 683646",
              "AssetId": 102949,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Empty",
              "Origin": "SOUTH GATE",
              "OriginState": "CA",
              "Destination": "YOUNGWOOD:ST GABRIEL:GEISMAR",
              "DestinationState": "LA",
              "LocationName": "Convent",
              "LocationState": "LA",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-15T03:04:40",
              "Duration": "148.10:30:00",
              "EtaDate": "2021-04-15T07:31:32.5",
              "EtaRailroadDate": "2021-04-16T13:00:00",
              "ArrivalStatus": "On Time",
              "Latitude": 30.075954437256,
              "Longitude": -90.884323120117,
              "WaybillIdentifier": "e2ce41e2-c5c5-4644-ad05-f1fa87d50fc8",
              "WaybillDestination": "GEISMAR",
              "WaybillDestinationState": "LA",
              "TrainID": "L51671",
              "ClmCode": "A",
              "ClmSightingDate": "2021-04-15T07:01:00",
              "ClmCodeDescription": "Arrival at an In - transit",
              "CareOfParty": "RUBICON LLC",
              "RailRoad": "CN",
              "BOL": null,
              "SID": null,
              "Customer": "INTELLITRANS INC",
              "CustPO": null,
              "Product": "TN",
              "NetWeight": null,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 649955",
              "AssetId": 92131,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Empty",
              "Origin": "TACOMA",
              "OriginState": "WA",
              "Destination": "YOUNGWOOD:ST GABRIEL:GEISMAR",
              "DestinationState": "LA",
              "LocationName": "Convent",
              "LocationState": "LA",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-15T03:04:22",
              "Duration": "142.09:30:00",
              "EtaDate": "2021-04-15T07:30:20.387",
              "EtaRailroadDate": "2021-04-16T13:00:00",
              "ArrivalStatus": "-",
              "Latitude": 30.079559326172,
              "Longitude": -90.890235900879,
              "WaybillIdentifier": "1f03ee02-7efa-4b03-89aa-5e25daa5c03f",
              "WaybillDestination": "GEISMAR",
              "WaybillDestinationState": "LA",
              "TrainID": "L51671",
              "ClmCode": "A",
              "ClmSightingDate": "2021-04-15T07:01:00",
              "ClmCodeDescription": "Arrival at an In - transit",
              "CareOfParty": "RUBICON LLC",
              "RailRoad": "CN",
              "BOL": null,
              "SID": null,
              "Customer": "INTELLITRANS INC",
              "CustPO": null,
              "Product": "TN",
              "NetWeight": null,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 661350",
              "AssetId": 70531,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "NEW ORLEANS",
              "OriginState": "LA",
              "Destination": "OLIVER YARD:NEW ORLEANS",
              "DestinationState": "LA",
              "LocationName": "New Orleans",
              "LocationState": "LA",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-15T02:38:46",
              "Duration": "00:00:00",
              "EtaDate": "2021-04-15T13:17:36",
              "EtaRailroadDate": null,
              "ArrivalStatus": "Late",
              "Latitude": 29.970645904541,
              "Longitude": -90.027183532715,
              "WaybillIdentifier": "d712e0c8-4fc6-4f0c-9ce0-a34a6f34baea",
              "WaybillDestination": "GRANDE PRAIRIE",
              "WaybillDestinationState": "AB",
              "TrainID": "",
              "ClmCode": "P",
              "ClmSightingDate": "2021-04-15T03:11:00",
              "ClmCodeDescription": "Departure",
              "CareOfParty": "GPR LOGISTICS PARK",
              "RailRoad": "NOPB",
              "BOL": 80868756,
              "SID": "2935764",
              "Customer": "HUNTSMAN POLYURETHANES INC.",
              "CustPO": "4570631478",
              "Product": "TN",
              "NetWeight": 186016,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 683663",
              "AssetId": 102938,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Empty",
              "Origin": "BARWICK",
              "OriginState": "ON",
              "Destination": "BARWICK",
              "DestinationState": "MN",
              "LocationName": "Fort Frances",
              "LocationState": "ON",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-14T21:25:14",
              "Duration": "00:00:00",
              "EtaDate": "2021-04-15T15:11:29",
              "EtaRailroadDate": null,
              "ArrivalStatus": "Late",
              "Latitude": 48.614086151123,
              "Longitude": -93.403442382813,
              "WaybillIdentifier": "af05b981-23da-402c-91a3-a8b52862ea87",
              "WaybillDestination": "GEISMAR",
              "WaybillDestinationState": "LA",
              "TrainID": "",
              "ClmCode": "W",
              "ClmSightingDate": "2021-04-12T11:57:00",
              "ClmCodeDescription": "Released",
              "CareOfParty": "RUBICON LLC",
              "RailRoad": "CN",
              "BOL": null,
              "SID": null,
              "Customer": "NORBORD INC.",
              "CustPO": null,
              "Product": "TN",
              "NetWeight": 0,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 683648",
              "AssetId": 102853,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "GEISMAR",
              "OriginState": "LA",
              "Destination": "YOUNGWOOD:ST GABRIEL:GEISMAR",
              "DestinationState": "LA",
              "LocationName": "Prichard",
              "LocationState": "MS",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-14T20:56:10",
              "Duration": "162.19:00:00",
              "EtaDate": "2021-04-15T15:51:55.387",
              "EtaRailroadDate": "2021-04-22T23:00:00",
              "ArrivalStatus": "-",
              "Latitude": 34.705131530762,
              "Longitude": -90.237861633301,
              "WaybillIdentifier": "4ddafcdd-04c8-412b-88a7-9b9ab74572c7",
              "WaybillDestination": "TWO HARBORS",
              "WaybillDestinationState": "MN",
              "TrainID": "M30171",
              "ClmCode": "P",
              "ClmSightingDate": "2021-04-15T13:43:00",
              "ClmCodeDescription": "Departure",
              "CareOfParty": "LOUISIANA PACIFIC CORP",
              "RailRoad": "CN",
              "BOL": 80868429,
              "SID": "2934641",
              "Customer": "HUNTSMAN POLYURETHANES INC.",
              "CustPO": "4570629213",
              "Product": "TN",
              "NetWeight": 187560,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 660863",
              "AssetId": 92362,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "GEISMAR",
              "OriginState": "LA",
              "Destination": "YOUNGWOOD:ST GABRIEL:GEISMAR",
              "DestinationState": "LA",
              "LocationName": "Lithium",
              "LocationState": "MO",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-14T19:11:40",
              "Duration": "6750.05:00:00",
              "EtaDate": "2021-04-17T11:49:03",
              "EtaRailroadDate": "2021-04-21T06:00:00",
              "ArrivalStatus": "-",
              "Latitude": 37.842136383057,
              "Longitude": -89.860969543457,
              "WaybillIdentifier": "f58a6d29-e7e1-442a-ace6-5e1ca5a3c704",
              "WaybillDestination": "NORTHWOOD SPUR",
              "WaybillDestinationState": "MN",
              "TrainID": "HMEMGA",
              "ClmCode": "P",
              "ClmSightingDate": "2021-04-15T13:48:00",
              "ClmCodeDescription": "Departure",
              "CareOfParty": "NORBORD MINNESOTA INC",
              "RailRoad": "BNSF",
              "BOL": 80867303,
              "SID": "2932865",
              "Customer": "INTELLITRANS INC",
              "CustPO": "4570625158",
              "Product": "TN",
              "NetWeight": 186880,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 660856",
              "AssetId": 92183,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Empty",
              "Origin": "HAYWARD JCT",
              "OriginState": "WI",
              "Destination": "HAYWARD JCT",
              "DestinationState": "WI",
              "LocationName": "Stanberry",
              "LocationState": "WI",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-14T15:07:10",
              "Duration": "27882.01:30:00",
              "EtaDate": "2021-04-22T09:00:17.5",
              "EtaRailroadDate": "2021-04-23T01:00:00",
              "ArrivalStatus": "On Time",
              "Latitude": 45.98950958252,
              "Longitude": -91.608169555664,
              "WaybillIdentifier": "f962b328-e302-4379-9070-6b2113d1dec6",
              "WaybillDestination": "GEISMAR",
              "WaybillDestinationState": "LA",
              "TrainID": "",
              "ClmCode": "W",
              "ClmSightingDate": "2021-04-14T19:47:00",
              "ClmCodeDescription": "Released",
              "CareOfParty": "RUBICON LLC",
              "RailRoad": "CN",
              "BOL": null,
              "SID": "N/S",
              "Customer": "LOUISIANA PACIFIC CORP",
              "CustPO": null,
              "Product": "TN",
              "NetWeight": 0,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 661347",
              "AssetId": 92385,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "GEISMAR",
              "OriginState": "LA",
              "Destination": "BREMEN",
              "DestinationState": "IN",
              "LocationName": "Montgomery",
              "LocationState": "AL",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-14T14:38:54",
              "Duration": "21033.10:00:00",
              "EtaDate": "2021-04-21T01:27:26",
              "EtaRailroadDate": null,
              "ArrivalStatus": "On Time",
              "Latitude": 32.408740997314,
              "Longitude": -86.325996398926,
              "WaybillIdentifier": "190970c2-da3a-4798-8081-e1300b167d68",
              "WaybillDestination": "BREMEN",
              "WaybillDestinationState": "IN",
              "TrainID": "",
              "ClmCode": "P",
              "ClmSightingDate": "2021-04-15T06:02:00",
              "ClmCodeDescription": "Departure",
              "CareOfParty": null,
              "RailRoad": "CSXT",
              "BOL": 72996839,
              "SID": "2930874",
              "Customer": "HUNTSMAN POLYURETHANES INC.",
              "CustPO": "4500584663 REL 20",
              "Product": "TN",
              "NetWeight": 188515,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 662387",
              "AssetId": 92272,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "NEW ORLEANS",
              "OriginState": "LA",
              "Destination": "OLIVER YARD:NEW ORLEANS",
              "DestinationState": "LA",
              "LocationName": "Southwest Memphis",
              "LocationState": "TN",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-14T11:21:22",
              "Duration": "42.12:00:00",
              "EtaDate": "2021-04-15T14:54:54",
              "EtaRailroadDate": "2021-04-20T12:00:00",
              "ArrivalStatus": "Late",
              "Latitude": 35.074642181396,
              "Longitude": -90.057655334473,
              "WaybillIdentifier": "30538199-a591-4c72-82f2-4e28f2293733",
              "WaybillDestination": "TOMAHAWK",
              "WaybillDestinationState": "WI",
              "TrainID": "A41971",
              "ClmCode": "A",
              "ClmSightingDate": "2021-04-15T08:16:00",
              "ClmCodeDescription": "Arrival at an In - transit",
              "CareOfParty": "LOUISIANA PACIFIC CORP",
              "RailRoad": "CN",
              "BOL": 80867938,
              "SID": "2933566",
              "Customer": "HUNTSMAN POLYURETHANES INC.",
              "CustPO": "4570629225",
              "Product": "TN",
              "NetWeight": 184395,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 683661",
              "AssetId": 102836,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "NEW ORLEANS",
              "OriginState": "LA",
              "Destination": "OLIVER YARD:NEW ORLEANS",
              "DestinationState": "LA",
              "LocationName": "Southwest Memphis",
              "LocationState": "TN",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-14T11:21:22",
              "Duration": "42.12:00:00",
              "EtaDate": "2021-04-15T14:53:38",
              "EtaRailroadDate": "2021-04-20T12:00:00",
              "ArrivalStatus": "Late",
              "Latitude": 35.074825286865,
              "Longitude": -90.056991577148,
              "WaybillIdentifier": "496bab6c-b21e-43be-9556-65ac7aa8a0e1",
              "WaybillDestination": "TOMAHAWK",
              "WaybillDestinationState": "WI",
              "TrainID": "A41971",
              "ClmCode": "A",
              "ClmSightingDate": "2021-04-15T08:16:00",
              "ClmCodeDescription": "Arrival at an In - transit",
              "CareOfParty": "LOUISIANA PACIFIC CORP",
              "RailRoad": "CN",
              "BOL": 80868081,
              "SID": "2933672",
              "Customer": "HUNTSMAN POLYURETHANES INC.",
              "CustPO": "4570629226",
              "Product": "TN",
              "NetWeight": 185925,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 679788",
              "AssetId": 96780,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Empty",
              "Origin": "GEISMAR",
              "OriginState": "LA",
              "Destination": "DEVON",
              "DestinationState": "KY",
              "LocationName": "Keene",
              "LocationState": "KY",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-14T10:48:04",
              "Duration": "7223.12:00:00",
              "EtaDate": "2021-04-17T15:02:34",
              "EtaRailroadDate": "2021-04-18T23:00:00",
              "ArrivalStatus": "On Time",
              "Latitude": 37.937305450439,
              "Longitude": -84.555717468262,
              "WaybillIdentifier": "27b57b5e-54e1-46c6-b1b1-a76709a09550",
              "WaybillDestination": "DEVON",
              "WaybillDestinationState": "KY",
              "TrainID": "",
              "ClmCode": "P",
              "ClmSightingDate": "2021-04-15T14:50:00",
              "ClmCodeDescription": "Departure",
              "CareOfParty": "FIRESTONE BUILDING PRODUCTS CO",
              "RailRoad": "NS",
              "BOL": 80865889,
              "SID": "2927317",
              "Customer": "RUBICON LLC",
              "CustPO": "4570630627",
              "Product": "TN",
              "NetWeight": 189200,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 649323",
              "AssetId": 92898,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Empty",
              "Origin": "LORENZO",
              "OriginState": "IL",
              "Destination": "YOUNGWOOD:ST GABRIEL:GEISMAR",
              "DestinationState": "LA",
              "LocationName": "Southwest Memphis",
              "LocationState": "TN",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-14T05:05:37",
              "Duration": "3577.00:30:00",
              "EtaDate": "2021-04-16T14:31:58.5",
              "EtaRailroadDate": "2021-04-18T01:00:00",
              "ArrivalStatus": "-",
              "Latitude": 35.034080505371,
              "Longitude": -90.129959106445,
              "WaybillIdentifier": "c32232fc-2bed-4d64-87c2-f7fc492e76bf",
              "WaybillDestination": "GEISMAR",
              "WaybillDestinationState": "LA",
              "TrainID": "Z19491",
              "ClmCode": "P",
              "ClmSightingDate": "2021-04-15T14:40:00",
              "ClmCodeDescription": "Departure",
              "CareOfParty": "RUBICON LLC",
              "RailRoad": "CN",
              "BOL": null,
              "SID": null,
              "Customer": "INTELLITRANS INC",
              "CustPO": null,
              "Product": "TN",
              "NetWeight": null,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 649834",
              "AssetId": 92419,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "GEISMAR",
              "OriginState": "LA",
              "Destination": "YOUNGWOOD:ST GABRIEL:GEISMAR",
              "DestinationState": "LA",
              "LocationName": "Southwest Memphis",
              "LocationState": "TN",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-13T21:06:23",
              "Duration": "162.19:00:00",
              "EtaDate": "2021-04-15T16:14:35.317",
              "EtaRailroadDate": "2021-04-22T23:00:00",
              "ArrivalStatus": "Late",
              "Latitude": 35.069969177246,
              "Longitude": -90.086212158203,
              "WaybillIdentifier": "9fa68114-51b8-4ef6-aaac-b82946819d6e",
              "WaybillDestination": "TWO HARBORS",
              "WaybillDestinationState": "MN",
              "TrainID": "M30171",
              "ClmCode": "A",
              "ClmSightingDate": "2021-04-14T14:35:00",
              "ClmCodeDescription": "Arrival at an In - transit",
              "CareOfParty": "LOUISIANA PACIFIC CORP",
              "RailRoad": "CN",
              "BOL": 80868969,
              "SID": "2933819",
              "Customer": "HUNTSMAN POLYURETHANES INC.",
              "CustPO": "4570633084",
              "Product": "TN",
              "NetWeight": 187987,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 679818",
              "AssetId": 96758,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "GEISMAR",
              "OriginState": "LA",
              "Destination": "EAST CORDELE",
              "DestinationState": "GA",
              "LocationName": "Wray",
              "LocationState": "GA",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-13T20:58:28",
              "Duration": "453.15:30:00",
              "EtaDate": "2021-04-15T18:11:26.86",
              "EtaRailroadDate": null,
              "ArrivalStatus": "Late",
              "Latitude": 31.620204925537,
              "Longitude": -83.052528381348,
              "WaybillIdentifier": "8c923560-29c3-4562-935f-216599726e0d",
              "WaybillDestination": "EAST CORDELE",
              "WaybillDestinationState": "GA",
              "TrainID": "",
              "ClmCode": "P",
              "ClmSightingDate": "2021-04-15T15:02:00",
              "ClmCodeDescription": "Departure",
              "CareOfParty": "NORBORD GEORGIA LLC",
              "RailRoad": "CSXT",
              "BOL": 80866938,
              "SID": "2930894",
              "Customer": "HUNTSMAN POLYURETHANES INC.",
              "CustPO": "4570631416",
              "Product": "TN",
              "NetWeight": 188550,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 683658",
              "AssetId": 102979,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "GEISMAR",
              "OriginState": "LA",
              "Destination": "KINARDS",
              "DestinationState": "SC",
              "LocationName": "Osierfield",
              "LocationState": "GA",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-13T20:35:46",
              "Duration": "21129.01:00:00",
              "EtaDate": "2021-04-21T11:51:59",
              "EtaRailroadDate": null,
              "ArrivalStatus": "On Time",
              "Latitude": 31.675712585449,
              "Longitude": -83.139976501465,
              "WaybillIdentifier": "e4c86f37-c215-4a62-8689-664df9655cd4",
              "WaybillDestination": "KINARDS",
              "WaybillDestinationState": "SC",
              "TrainID": "",
              "ClmCode": "P",
              "ClmSightingDate": "2021-04-15T15:02:00",
              "ClmCodeDescription": "Departure",
              "CareOfParty": "NORBORD SOUTH CAROLINA INC",
              "RailRoad": "CSXT",
              "BOL": 80867304,
              "SID": "2930672",
              "Customer": "HUNTSMAN POLYURETHANES INC.",
              "CustPO": "4570628715",
              "Product": "TN",
              "NetWeight": 187860,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 642449",
              "AssetId": 92204,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Empty",
              "Origin": "TERRELL",
              "OriginState": "TX",
              "Destination": "TERRELL",
              "DestinationState": "TX",
              "LocationName": "North Little Rock",
              "LocationState": "AR",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-13T20:07:28",
              "Duration": "00:00:00",
              "EtaDate": "2021-04-15T10:37:58",
              "EtaRailroadDate": "2021-04-21T13:00:00",
              "ArrivalStatus": "Late",
              "Latitude": 34.750659942627,
              "Longitude": -92.287605285645,
              "WaybillIdentifier": "f106046d-604d-4372-a962-208c9fff9af8",
              "WaybillDestination": "GEISMAR",
              "WaybillDestinationState": "LA",
              "TrainID": "MDANL1",
              "ClmCode": "A",
              "ClmSightingDate": "2021-04-15T10:49:00",
              "ClmCodeDescription": "Arrival at an In - transit",
              "CareOfParty": null,
              "RailRoad": "UP",
              "BOL": null,
              "SID": null,
              "Customer": "RUBICON",
              "CustPO": null,
              "Product": "RR",
              "NetWeight": null,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 665226",
              "AssetId": 92350,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Empty",
              "Origin": "YOUNGWOOD",
              "OriginState": "PA",
              "Destination": "YOUNGWOOD:ST GABRIEL:GEISMAR",
              "DestinationState": "LA",
              "LocationName": "Connellsville",
              "LocationState": "PA",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-13T14:18:54",
              "Duration": "70904.05:30:00",
              "EtaDate": "2021-05-05T07:49:15.5",
              "EtaRailroadDate": null,
              "ArrivalStatus": "On Time",
              "Latitude": 40.017333984375,
              "Longitude": -79.59203338623,
              "WaybillIdentifier": "e9b7496e-08b1-46b8-bab9-e3459da45f95",
              "WaybillDestination": "GEISMAR",
              "WaybillDestinationState": "LA",
              "TrainID": "SWP",
              "ClmCode": "R",
              "ClmSightingDate": "2021-04-14T13:40:00",
              "ClmCodeDescription": "Junction Received",
              "CareOfParty": "RUBICON LLC",
              "RailRoad": "CSXT",
              "BOL": null,
              "SID": null,
              "Customer": "FIRESTONE BUILDING PRODUCTS CO",
              "CustPO": null,
              "Product": "RR",
              "NetWeight": null,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 679794",
              "AssetId": 96745,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "GEISMAR",
              "OriginState": "LA",
              "Destination": "YOUNGWOOD:ST GABRIEL:GEISMAR",
              "DestinationState": "LA",
              "LocationName": "Shreveport",
              "LocationState": "LA",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-13T12:32:52",
              "Duration": "162.11:00:00",
              "EtaDate": "2021-04-15T05:18:03",
              "EtaRailroadDate": "2021-04-20T23:00:00",
              "ArrivalStatus": "Late",
              "Latitude": 32.534465789795,
              "Longitude": -93.835632324219,
              "WaybillIdentifier": "fcc3ac2e-e026-45f5-b28f-10590644ff3d",
              "WaybillDestination": "TULA",
              "WaybillDestinationState": "HG",
              "TrainID": "",
              "ClmCode": "A",
              "ClmSightingDate": "2021-04-14T02:58:00",
              "ClmCodeDescription": "Arrival at an In - transit",
              "CareOfParty": "FR TERMINALES SA DE CV",
              "RailRoad": "KCS",
              "BOL": 72998708,
              "SID": "2933801",
              "Customer": "HUNTSMAN CORP",
              "CustPO": "3609",
              "Product": "RR",
              "NetWeight": 189290,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 642508",
              "AssetId": 92218,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Empty",
              "Origin": "LA SARRE",
              "OriginState": "PQ",
              "Destination": "YOUNGWOOD:ST GABRIEL:GEISMAR",
              "DestinationState": "LA",
              "LocationName": "East Chicago",
              "LocationState": "IN",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-13T06:09:46",
              "Duration": "14400.03:00:00",
              "EtaDate": "2021-04-19T14:31:49",
              "EtaRailroadDate": "2021-04-21T01:00:00",
              "ArrivalStatus": "Late",
              "Latitude": 41.619499206543,
              "Longitude": -87.425804138184,
              "WaybillIdentifier": "9e15f70b-79c4-4379-8138-abddfcd22905",
              "WaybillDestination": "GEISMAR",
              "WaybillDestinationState": "LA",
              "TrainID": "X49791",
              "ClmCode": "P",
              "ClmSightingDate": "2021-04-15T14:57:00",
              "ClmCodeDescription": "Departure",
              "CareOfParty": "RUBICON LLC",
              "RailRoad": "CN",
              "BOL": null,
              "SID": null,
              "Customer": "NORBORD INC.",
              "CustPO": null,
              "Product": "TN",
              "NetWeight": 0,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 664137",
              "AssetId": 92175,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Empty",
              "Origin": "TACOMA",
              "OriginState": "WA",
              "Destination": "YOUNGWOOD:ST GABRIEL:GEISMAR",
              "DestinationState": "LA",
              "LocationName": "Paradise",
              "LocationState": "MT",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-13T03:44:58",
              "Duration": "62119.12:00:00",
              "EtaDate": "2021-05-02T20:58:22",
              "EtaRailroadDate": "2021-04-29T22:00:00",
              "ArrivalStatus": "On Time",
              "Latitude": 47.3141746521,
              "Longitude": -114.832252502441,
              "WaybillIdentifier": "757f3fdc-a5b4-4030-8811-071c11b0f54b",
              "WaybillDestination": "GEISMAR",
              "WaybillDestinationState": "LA",
              "TrainID": "HPASLA",
              "ClmCode": "P",
              "ClmSightingDate": "2021-04-15T11:00:00",
              "ClmCodeDescription": "Departure",
              "CareOfParty": "RUBICON LLC",
              "RailRoad": "MRL",
              "BOL": null,
              "SID": null,
              "Customer": "INTELLITRANS INC",
              "CustPO": null,
              "Product": "TN",
              "NetWeight": null,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 683719",
              "AssetId": 102847,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "GEISMAR",
              "OriginState": "LA",
              "Destination": "MAYO CREEK",
              "DestinationState": "NC",
              "LocationName": "Champaign",
              "LocationState": "IL",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-12T20:28:34",
              "Duration": "00:00:00",
              "EtaDate": "2021-04-15T09:51:40",
              "EtaRailroadDate": "2021-04-21T01:00:00",
              "ArrivalStatus": "Late",
              "Latitude": 40.108810424805,
              "Longitude": -88.242393493652,
              "WaybillIdentifier": "312dfcd8-2dd7-4b78-9b1c-00d1775c1859",
              "WaybillDestination": "NEW LIMERICK",
              "WaybillDestinationState": "ME",
              "TrainID": "M33571",
              "ClmCode": "A",
              "ClmSightingDate": "2021-04-15T09:47:00",
              "ClmCodeDescription": "Arrival at an In - transit",
              "CareOfParty": "LOUISIANA PACIFIC CORP",
              "RailRoad": "CN",
              "BOL": 80868325,
              "SID": "2933803",
              "Customer": "HUNTSMAN POLYURETHANES INC.",
              "CustPO": "4570632535",
              "Product": "TN",
              "NetWeight": 187980,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 662204",
              "AssetId": 93264,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "GEISMAR",
              "OriginState": "LA",
              "Destination": "COMMERCE",
              "DestinationState": "GA",
              "LocationName": "Clifton",
              "LocationState": "IL",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-12T20:28:04",
              "Duration": "00:00:00",
              "EtaDate": "2021-04-15T14:54:01",
              "EtaRailroadDate": "2021-04-22T23:00:00",
              "ArrivalStatus": "Late",
              "Latitude": 40.915939331055,
              "Longitude": -87.941917419434,
              "WaybillIdentifier": "29fb29dc-db30-4739-a055-5c3e9d591ce1",
              "WaybillDestination": "TWO HARBORS",
              "WaybillDestinationState": "MN",
              "TrainID": "M33571",
              "ClmCode": "A",
              "ClmSightingDate": "2021-04-15T15:05:00",
              "ClmCodeDescription": "Arrival at an In - transit",
              "CareOfParty": "LOUISIANA PACIFIC CORP",
              "RailRoad": "CN",
              "BOL": 80867808,
              "SID": "2933728",
              "Customer": "HUNTSMAN POLYURETHANES INC.",
              "CustPO": "4570629212",
              "Product": "TN",
              "NetWeight": 189040,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 646242",
              "AssetId": 92189,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "GEISMAR",
              "OriginState": "LA",
              "Destination": "CRYSTAL HILL",
              "DestinationState": "VA",
              "LocationName": "Hutchins",
              "LocationState": "TX",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-12T12:45:34",
              "Duration": "32325.06:00:00",
              "EtaDate": "2021-04-24T12:15:40",
              "EtaRailroadDate": "2021-04-15T20:00:00",
              "ArrivalStatus": "Late",
              "Latitude": 32.711059570313,
              "Longitude": -96.748741149902,
              "WaybillIdentifier": "57d02572-e3ea-4766-807b-cc4154835afe",
              "WaybillDestination": "TERRELL",
              "WaybillDestinationState": "TX",
              "TrainID": "MFWDAB",
              "ClmCode": "A",
              "ClmSightingDate": "2021-04-15T00:09:00",
              "ClmCodeDescription": "Arrival at an In - transit",
              "CareOfParty": "CARLISLE CONSTRUCTION MATERI",
              "RailRoad": "UP",
              "BOL": 72997101,
              "SID": "2933733",
              "Customer": "RUBICON",
              "CustPO": "10451476",
              "Product": "RR",
              "NetWeight": 188540,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 683709",
              "AssetId": 102945,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "GEISMAR",
              "OriginState": "LA",
              "Destination": "TACOMA",
              "DestinationState": "WA",
              "LocationName": "Fridley",
              "LocationState": "MN",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-12T09:11:16.45",
              "Duration": "22350.00:30:00",
              "EtaDate": "2021-04-21T06:30:22.5",
              "EtaRailroadDate": "2021-04-27T18:00:00",
              "ArrivalStatus": "-",
              "Latitude": 45.074577331543,
              "Longitude": -93.271125793457,
              "WaybillIdentifier": "7dcbe27f-5c0a-46df-aa70-34078a6e7772",
              "WaybillDestination": "TACOMA",
              "WaybillDestinationState": "WA",
              "TrainID": "HGALGF",
              "ClmCode": "A",
              "ClmSightingDate": "2021-04-14T23:58:00",
              "ClmCodeDescription": "Arrival at an In - transit",
              "CareOfParty": "CARLISLE CONSTRUCTION MATERIALS INC",
              "RailRoad": "BNSF",
              "BOL": 72995881,
              "SID": "2930674",
              "Customer": "INTELLITRANS INC",
              "CustPO": "10459975",
              "Product": "TN",
              "NetWeight": 188540,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 642507",
              "AssetId": 92232,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Empty",
              "Origin": "GEISMAR",
              "OriginState": "LA",
              "Destination": "MAYO CREEK",
              "DestinationState": "NC",
              "LocationName": "Roanoke",
              "LocationState": "VA",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-12T05:44:34",
              "Duration": "11250.05:00:00",
              "EtaDate": "2021-04-18T11:32:51",
              "EtaRailroadDate": null,
              "ArrivalStatus": "-",
              "Latitude": 37.271514892578,
              "Longitude": -79.997970581055,
              "WaybillIdentifier": "0da2314e-2707-44a1-b1a6-ee9aa28fd7c9",
              "WaybillDestination": "ORANGE",
              "WaybillDestinationState": "TX",
              "TrainID": "",
              "ClmCode": "W",
              "ClmSightingDate": "2021-04-14T12:51:00",
              "ClmCodeDescription": "Released",
              "CareOfParty": null,
              "RailRoad": "BNSF",
              "BOL": null,
              "SID": "EMPTYCARMOVE",
              "Customer": "RUBICON",
              "CustPO": "EAGLESHOPORANGE",
              "Product": "RR",
              "NetWeight": null,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 665234",
              "AssetId": 92206,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "GEISMAR",
              "OriginState": "LA",
              "Destination": "LORENZO",
              "DestinationState": "IL",
              "LocationName": "Maplewood",
              "LocationState": "MO",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-12T02:14:58",
              "Duration": "13879.19:00:00",
              "EtaDate": "2021-04-19T11:04:41.383",
              "EtaRailroadDate": "2021-04-20T00:00:00",
              "ArrivalStatus": "Late",
              "Latitude": 38.614284515381,
              "Longitude": -90.301063537598,
              "WaybillIdentifier": "ce88dff8-29fe-4d9a-ae73-3652a25bebef",
              "WaybillDestination": "LORENZO",
              "WaybillDestinationState": "IL",
              "TrainID": "",
              "ClmCode": "P",
              "ClmSightingDate": "2021-04-15T14:52:00",
              "ClmCodeDescription": "Departure",
              "CareOfParty": "OMEGA PARTNERS JOLIET LLC",
              "RailRoad": "BNSF",
              "BOL": 80867841,
              "SID": "2932213",
              "Customer": "INTELLITRANS INC",
              "CustPO": "4570631915",
              "Product": "TN",
              "NetWeight": 189100,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 664467",
              "AssetId": 93271,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "GEISMAR",
              "OriginState": "LA",
              "Destination": "NEW LIMERICK",
              "DestinationState": "ME",
              "LocationName": "Stockholm",
              "LocationState": "ME",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-11T20:40:41",
              "Duration": "59109.00:00:00",
              "EtaDate": "2021-05-01T23:55:41",
              "EtaRailroadDate": "2021-04-15T20:00:00",
              "ArrivalStatus": "On Time",
              "Latitude": 47.17036819458,
              "Longitude": -67.943016052246,
              "WaybillIdentifier": "bbd7b7af-a877-4f16-9c82-4b21784ebf35",
              "WaybillDestination": "NEW LIMERICK",
              "WaybillDestinationState": "ME",
              "TrainID": "",
              "ClmCode": "A",
              "ClmSightingDate": "2021-04-15T12:45:00",
              "ClmCodeDescription": "Arrival at an In - transit",
              "CareOfParty": "LOUISIANA PACIFIC CORP",
              "RailRoad": "MNR",
              "BOL": 80868324,
             "SID": "2930620",
              "Customer": "HUNTSMAN POLYURETHANES INC.",
              "CustPO": "4570632534",
              "Product": "TN",
              "NetWeight": 186960,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 644376",
              "AssetId": 93299,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Empty",
              "Origin": "NEW LIMERICK",
              "OriginState": "ME",
              "Destination": "NEW LIMERICK",
              "DestinationState": "ME",
              "LocationName": "Grand Isle",
              "LocationState": "ME",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-11T18:50:46",
              "Duration": "00:00:00",
              "EtaDate": "2021-04-15T04:32:55.457",
              "EtaRailroadDate": "2021-04-24T13:00:00",
              "ArrivalStatus": "Late",
              "Latitude": 47.18493270874,
              "Longitude": -67.941070556641,
              "WaybillIdentifier": "d6bc43ba-2119-4757-914d-edca8075e43c",
              "WaybillDestination": "GEISMAR",
              "WaybillDestinationState": "LA",
              "TrainID": "L57811",
              "ClmCode": "A",
              "ClmSightingDate": "2021-04-15T05:09:00",
              "ClmCodeDescription": "Arrival at an In - transit",
              "CareOfParty": "KINDER MORGAN LIQUID TERMINALS LLC",
              "RailRoad": "CN",
              "BOL": null,
              "SID": null,
              "Customer": "KINDER MORGAN LIQUID TERMINALS LLC",
              "CustPO": null,
              "Product": "TN",
              "NetWeight": 0,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 660880",
              "AssetId": 93199,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Empty",
              "Origin": "TWO HARBORS",
              "OriginState": "MN",
              "Destination": "YOUNGWOOD:ST GABRIEL:GEISMAR",
              "DestinationState": "LA",
              "LocationName": "Southwest Memphis",
              "LocationState": "TN",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-11T18:25:58",
              "Duration": "3659.17:00:00",
              "EtaDate": "2021-04-16T15:05:04",
              "EtaRailroadDate": "2021-04-18T01:00:00",
              "ArrivalStatus": "-",
              "Latitude": 35.036697387695,
              "Longitude": -90.130004882813,
              "WaybillIdentifier": "c65fe0a8-16eb-41b4-a19c-e22efd2b0828",
              "WaybillDestination": "GEISMAR",
              "WaybillDestinationState": "LA",
              "TrainID": "Z19491",
              "ClmCode": "P",
              "ClmSightingDate": "2021-04-15T14:40:00",
              "ClmCodeDescription": "Departure",
              "CareOfParty": "RUBICON LLC",
              "RailRoad": "CN",
              "BOL": null,
              "SID": null,
              "Customer": "LOUISIANA PACIFIC CORP",
              "CustPO": null,
              "Product": "TN",
              "NetWeight": 0,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 679796",
              "AssetId": 96809,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Empty",
              "Origin": "HAYWARD JCT",
              "OriginState": "WI",
              "Destination": "YOUNGWOOD:ST GABRIEL:GEISMAR",
              "DestinationState": "LA",
              "LocationName": "Southwest Memphis",
              "LocationState": "TN",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-11T18:25:58",
              "Duration": "5508.21:00:00",
              "EtaDate": "2021-04-17T01:19:37",
              "EtaRailroadDate": "2021-04-19T01:00:00",
              "ArrivalStatus": "-",
              "Latitude": 35.067886352539,
              "Longitude": -90.089736938477,
              "WaybillIdentifier": "692debed-a111-4a9d-817c-813df43be9d5",
              "WaybillDestination": "GEISMAR",
              "WaybillDestinationState": "LA",
              "TrainID": "O  999",
              "ClmCode": "B",
              "ClmSightingDate": "2021-04-14T10:32:00",
              "ClmCodeDescription": "Bad Orders",
              "CareOfParty": "RUBICON LLC",
              "RailRoad": "CN",
              "BOL": null,
              "SID": "N/S",
              "Customer": "LOUISIANA PACIFIC CORP",
              "CustPO": null,
              "Product": "TN",
              "NetWeight": 0,
              "DefaultJsonData": null
          },
          {
             "Asset": "UTLX 683720",
              "AssetId": 102976,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Empty",
              "Origin": "NORTHWOOD SPUR",
              "OriginState": "MN",
              "Destination": "YOUNGWOOD:ST GABRIEL:GEISMAR",
              "DestinationState": "LA",
              "LocationName": "Birmingham",
              "LocationState": "AL",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-11T11:34:22",
              "Duration": "2584.18:00:00",
              "EtaDate": "2021-04-16T08:02:58",
              "EtaRailroadDate": "2021-04-20T01:00:00",
              "ArrivalStatus": "Late",
              "Latitude": 33.520286560059,
              "Longitude": -86.871315002441,
              "WaybillIdentifier": "232c5204-c29d-4054-8573-bbfcfeb8314f",
              "WaybillDestination": "GEISMAR",
              "WaybillDestinationState": "LA",
              "TrainID": "",
              "ClmCode": "P",
              "ClmSightingDate": "2021-04-15T14:50:00",
              "ClmCodeDescription": "Departure",
              "CareOfParty": "RUBICON LLC",
              "RailRoad": "BNSF",
              "BOL": null,
              "SID": null,
              "Customer": "INTELLITRANS INC",
              "CustPO": null,
              "Product": "TN",
              "NetWeight": null,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 660858",
              "AssetId": 93190,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "NEW ORLEANS",
              "OriginState": "LA",
              "Destination": "GRANDE PRAIRIE",
              "DestinationState": "AB",
              "LocationName": "Munger",
              "LocationState": "MN",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-11T10:06:00.397",
              "Duration": "39084.00:00:00",
              "EtaDate": "2021-04-26T11:01:28",
              "EtaRailroadDate": "2021-04-21T14:00:00",
              "ArrivalStatus": "-",
              "Latitude": 46.800876617432,
              "Longitude": -92.350006103516,
              "WaybillIdentifier": "5d322f4a-76ed-4f01-92d9-809f6a59429f",
              "WaybillDestination": "GRANDE PRAIRIE",
              "WaybillDestinationState": "AB",
              "TrainID": "M34791",
              "ClmCode": "P",
              "ClmSightingDate": "2021-04-15T14:06:00",
              "ClmCodeDescription": "Departure",
              "CareOfParty": "GPR LOGISTICS PARK",
              "RailRoad": "CN",
              "BOL": 80867793,
              "SID": "2932095",
              "Customer": "HUNTSMAN POLYURETHANES INC.",
              "CustPO": "4570631477",
              "Product": "TN",
              "NetWeight": 185114,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 664470",
              "AssetId": 93246,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "-",
              "Origin": "Mays Yard",
              "OriginState": "LA",
              "Destination": "YOUNGWOOD:ST GABRIEL:GEISMAR",
              "DestinationState": "LA",
              "LocationName": "Larsen",
              "LocationState": "WI",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-11T10:05:54.37",
              "Duration": "40.15:00:00",
              "EtaDate": "2021-04-15T15:09:49",
              "EtaRailroadDate": "2021-04-17T23:00:00",
              "ArrivalStatus": "Late",
              "Latitude": 44.208435058594,
              "Longitude": -88.580307006836,
              "WaybillIdentifier": null,
              "WaybillDestination": null,
              "WaybillDestinationState": null,
              "TrainID": "A49191",
              "ClmCode": "P",
              "ClmSightingDate": "2021-04-15T14:38:00",
              "ClmCodeDescription": "Departure",
              "CareOfParty": null,
              "RailRoad": "CN",
              "BOL": null,
              "SID": null,
              "Customer": null,
              "CustPO": null,
              "Product": null,
              "NetWeight": null,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 650541",
              "AssetId": 92767,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Empty",
              "Origin": "SALT LAKE CITY",
              "OriginState": "UT",
              "Destination": "YOUNGWOOD:ST GABRIEL:GEISMAR",
              "DestinationState": "LA",
              "LocationName": "Avondale",
              "LocationState": "LA",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-11T05:25:28",
              "Duration": "28019.11:30:00",
              "EtaDate": "2021-04-23T06:41:51.5",
              "EtaRailroadDate": "2021-04-18T01:00:00",
              "ArrivalStatus": "-",
              "Latitude": 29.917510986328,
              "Longitude": -90.194068908691,
              "WaybillIdentifier": "795aea70-e41a-4c2a-a3fe-1fe13919047f",
              "WaybillDestination": "GEISMAR",
              "WaybillDestinationState": "LA",
              "TrainID": "HLALCS",
              "ClmCode": "A",
              "ClmSightingDate": "2021-04-14T11:01:00",
              "ClmCodeDescription": "Arrival at an In - transit",
              "CareOfParty": "RUBICON LLC",
              "RailRoad": "BNSF",
              "BOL": null,
              "SID": null,
              "Customer": "RSI LOGISTICS INC",
              "CustPO": null,
              "Product": "TN",
              "NetWeight": null,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 664134",
              "AssetId": 92305,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "GEISMAR",
              "OriginState": "LA",
              "Destination": "BREMEN",
              "DestinationState": "IN",
              "LocationName": "Nappanee",
              "LocationState": "IN",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-10T23:05:01",
              "Duration": "338.17:00:00",
              "EtaDate": "2021-04-15T16:48:05.393",
              "EtaRailroadDate": null,
              "ArrivalStatus": "Late",
              "Latitude": 41.442417144775,
              "Longitude": -86.021636962891,
              "WaybillIdentifier": "a491f4ea-9c45-419d-93d2-239a7ffc970f",
              "WaybillDestination": "BREMEN",
              "WaybillDestinationState": "IN",
              "TrainID": "",
              "ClmCode": "P",
              "ClmSightingDate": "2021-04-15T13:52:00",
              "ClmCodeDescription": "Departure",
              "CareOfParty": null,
              "RailRoad": "CSXT",
              "BOL": 72995844,
              "SID": "2927568",
              "Customer": "HUNTSMAN POLYURETHANES INC.",
              "CustPO": "4500576186 REL 90",
              "Product": "TN",
              "NetWeight": 188570,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 650533",
              "AssetId": 93198,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "GEISMAR",
              "OriginState": "LA",
              "Destination": "BREMEN",
              "DestinationState": "IN",
              "LocationName": "Nappanee",
              "LocationState": "IN",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-10T23:04:59",
              "Duration": "338.17:00:00",
              "EtaDate": "2021-04-15T16:48:09",
              "EtaRailroadDate": null,
              "ArrivalStatus": "Late",
              "Latitude": 41.442398071289,
              "Longitude": -86.021522521973,
              "WaybillIdentifier": "596505aa-0787-4b52-adc2-ac9a606f4414",
              "WaybillDestination": "BREMEN",
              "WaybillDestinationState": "IN",
              "TrainID": "",
              "ClmCode": "P",
              "ClmSightingDate": "2021-04-15T13:52:00",
              "ClmCodeDescription": "Departure",
              "CareOfParty": null,
              "RailRoad": "CSXT",
              "BOL": 72995841,
              "SID": "2927508",
              "Customer": "HUNTSMAN POLYURETHANES INC.",
              "CustPO": "4500576186 REL 80",
              "Product": "TN",
              "NetWeight": 189950,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 679806",
              "AssetId": 96781,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "GEISMAR",
              "OriginState": "LA",
              "Destination": "NEW LIMERICK",
              "DestinationState": "ME",
              "LocationName": "Wallagrass",
              "LocationState": "ME",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-10T14:36:58",
              "Duration": "41560.09:00:00",
              "EtaDate": "2021-04-27T03:59:44",
              "EtaRailroadDate": "2021-04-17T16:00:00",
              "ArrivalStatus": "On Time",
              "Latitude": 47.110557556152,
              "Longitude": -68.585639953613,
              "WaybillIdentifier": "5e021005-7386-49d3-88fd-48e5d21b6425",
              "WaybillDestination": "NEW LIMERICK",
              "WaybillDestinationState": "ME",
              "TrainID": "",
              "ClmCode": "P",
              "ClmSightingDate": "2021-04-15T12:15:00",
              "ClmCodeDescription": "Departure",
              "CareOfParty": "LOUISIANA PACIFIC CORP",
              "RailRoad": "MNR",
              "BOL": 80868323,
              "SID": "2930567",
              "Customer": "HUNTSMAN POLYURETHANES INC.",
              "CustPO": "4570632533",
              "Product": "TN",
              "NetWeight": 188210,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 650530",
              "AssetId": 92372,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "GEISMAR",
              "OriginState": "LA",
              "Destination": "SALT LAKE CITY",
              "DestinationState": "UT",
              "LocationName": "Mountain View",
              "LocationState": "CO",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-10T08:57:30",
              "Duration": "30610.21:30:00",
              "EtaDate": "2021-04-23T03:54:13.5",
              "EtaRailroadDate": "2021-04-19T18:00:00",
              "ArrivalStatus": "On Time",
              "Latitude": 39.762233734131,
              "Longitude": -104.995147705078,
              "WaybillIdentifier": "286bb864-53fe-4b8e-bca8-644553441e58",
              "WaybillDestination": "SALT LAKE CITY",
              "WaybillDestinationState": "UT",
              "TrainID": "HSLADE",
              "ClmCode": "A",
              "ClmSightingDate": "2021-04-14T13:23:00",
              "ClmCodeDescription": "Arrival at an In - transit",
              "CareOfParty": "UNIVAR SOLUTIONS USA INC",
              "RailRoad": "BNSF",
              "BOL": 80866760,
              "SID": "2928585",
              "Customer": "RSI LOGISTICS INC",
              "CustPO": "4570631066",
              "Product": "TN",
              "NetWeight": 187300,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 650150",
              "AssetId": 92168,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Empty",
              "Origin": "SALT LAKE CITY",
              "OriginState": "UT",
              "Destination": "YOUNGWOOD:ST GABRIEL:GEISMAR",
              "DestinationState": "LA",
              "LocationName": "Orange",
              "LocationState": "TX",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-10T00:46:46",
              "Duration": "8105.11:00:00",
              "EtaDate": "2021-04-17T20:30:52",
              "EtaRailroadDate": "2021-04-21T01:00:00",
              "ArrivalStatus": "Late",
              "Latitude": 30.149890899658,
              "Longitude": -93.744827270508,
              "WaybillIdentifier": "ab5d29e1-22ad-42bf-a703-bcccad36c780",
              "WaybillDestination": "GEISMAR",
              "WaybillDestinationState": "LA",
              "TrainID": "MLKBT1",
              "ClmCode": "P",
              "ClmSightingDate": "2021-04-15T14:43:00",
              "ClmCodeDescription": "Departure",
              "CareOfParty": "RUBICON LLC",
              "RailRoad": "UP",
              "BOL": null,
              "SID": null,
              "Customer": "RSI LOGISTICS INC",
              "CustPO": null,
              "Product": "TN",
              "NetWeight": null,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 662198",
              "AssetId": 92233,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Empty",
              "Origin": "GEISMAR",
              "OriginState": "LA",
              "Destination": "CRYSTAL HILL",
              "DestinationState": "VA",
              "LocationName": "Chattanooga",
              "LocationState": "TN",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-09T20:37:52",
              "Duration": "00:00:00",
              "EtaDate": "2021-04-15T13:07:35",
              "EtaRailroadDate": "2021-04-20T01:00:00",
              "ArrivalStatus": "Late",
              "Latitude": 35.059101104736,
              "Longitude": -85.271064758301,
              "WaybillIdentifier": "01c900fd-8226-4a7e-a588-c669bac8f750",
              "WaybillDestination": "CRYSTAL HILL",
              "WaybillDestinationState": "VA",
              "TrainID": "",
              "ClmCode": "P",
              "ClmSightingDate": "2021-04-15T08:21:00",
              "ClmCodeDescription": "Departure",
              "CareOfParty": null,
              "RailRoad": "NS",
              "BOL": 72991427,
              "SID": "2924973",
              "Customer": "HUNTSMAN POLYURETHANES INC.",
              "CustPO": "385511 R2",
              "Product": "TN",
              "NetWeight": 188970,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 679753",
              "AssetId": 96768,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Empty",
              "Origin": "BRISTOL",
              "OriginState": "CT",
              "Destination": "YOUNGWOOD:ST GABRIEL:GEISMAR",
              "DestinationState": "LA",
              "LocationName": "Shenandoah Junction",
              "LocationState": "WV",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-09T19:52:04",
              "Duration": "967363.01:00:00",
              "EtaDate": "2022-01-09T06:33:35.383",
              "EtaRailroadDate": "2021-04-17T00:00:00",
              "ArrivalStatus": "On Time",
              "Latitude": 39.355728149414,
              "Longitude": -77.844871520996,
              "WaybillIdentifier": "703d2946-a0d7-4e48-9928-9214078d6753",
              "WaybillDestination": "GEISMAR",
              "WaybillDestinationState": "LA",
              "TrainID": "",
              "ClmCode": "P",
              "ClmSightingDate": "2021-04-15T12:56:00",
              "ClmCodeDescription": "Departure",
              "CareOfParty": "RUBICON LLC",
              "RailRoad": "NS",
              "BOL": null,
              "SID": null,
              "Customer": "RUBICON LLC",
              "CustPO": null,
              "Product": "RR",
              "NetWeight": null,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 683722",
              "AssetId": 102790,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "GEISMAR",
              "OriginState": "LA",
              "Destination": "GUNTOWN",
              "DestinationState": "MS",
              "LocationName": "Artesia",
              "LocationState": "MS",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-09T16:20:08",
              "Duration": "12391.20:00:00",
              "EtaDate": "2021-04-18T16:30:17.44",
              "EtaRailroadDate": "2021-04-15T13:00:00",
              "ArrivalStatus": "Late",
              "Latitude": 33.414173126221,
              "Longitude": -88.643005371094,
              "WaybillIdentifier": "df59cab5-c326-46c0-8167-72c871af4f6f",
              "WaybillDestination": "GUNTOWN",
              "WaybillDestinationState": "MS",
              "TrainID": "",
              "ClmCode": "A",
              "ClmSightingDate": "2021-04-13T14:21:00",
              "ClmCodeDescription": "Arrival at an In - transit",
              "CareOfParty": "NORBORD MISSISSIPPI INC",
              "RailRoad": "KCS",
              "BOL": 80868121,
              "SID": "2930892",
              "Customer": "HUNTSMAN CORP",
              "CustPO": "4570632319",
              "Product": "RR",
              "NetWeight": 187290,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 683678",
              "AssetId": 102865,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "NEW ORLEANS",
              "OriginState": "LA",
              "Destination": "TOMAHAWK",
              "DestinationState": "WI",
              "LocationName": "Irma",
              "LocationState": "WI",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-09T07:57:35",
              "Duration": "150.21:30:00",
              "EtaDate": "2021-04-15T05:24:07.5",
              "EtaRailroadDate": "2021-04-14T20:00:00",
              "ArrivalStatus": "Late",
              "Latitude": 45.297710418701,
              "Longitude": -89.690620422363,
              "WaybillIdentifier": "6f7156f9-d426-46cb-aadf-a7cbc24734c5",
              "WaybillDestination": "TOMAHAWK",
              "WaybillDestinationState": "WI",
              "TrainID": "L58981",
              "ClmCode": "A",
              "ClmSightingDate": "2021-04-15T04:49:00",
              "ClmCodeDescription": "Arrival at an In - transit",
              "CareOfParty": "LOUISIANA PACIFIC CORP",
              "RailRoad": "CN",
              "BOL": 80866887,
              "SID": "2930808",
              "Customer": "HUNTSMAN POLYURETHANES INC.",
              "CustPO": "4570629223",
              "Product": "TN",
              "NetWeight": 184486,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 665157",
              "AssetId": 103813,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "GEISMAR",
              "OriginState": "LA",
              "Destination": "SAGOLA",
              "DestinationState": "MI",
              "LocationName": "Sagola",
              "LocationState": "MI",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-08T07:11:46",
              "Duration": "75.00:00:00",
              "EtaDate": "2021-04-15T15:42:53",
              "EtaRailroadDate": "2021-04-15T15:00:00",
              "ArrivalStatus": "Late",
              "Latitude": 46.040222167969,
              "Longitude": -88.066253662109,
              "WaybillIdentifier": "1ac8d1ab-94ae-428c-82a3-0d7a29032f13",
              "WaybillDestination": "SAGOLA",
              "WaybillDestinationState": "MI",
              "TrainID": "",
              "ClmCode": "Z",
              "ClmSightingDate": "2021-04-13T15:50:00",
              "ClmCodeDescription": "Actual Placement",
              "CareOfParty": "LOUISIANA PACIFIC CORP",
              "RailRoad": "ELS",
              "BOL": 80866747,
              "SID": "2929339",
              "Customer": "HUNTSMAN POLYURETHANES INC.",
              "CustPO": "4570629172",
              "Product": "TN",
              "NetWeight": 187790,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 679801",
              "AssetId": 96837,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "GEISMAR",
              "OriginState": "LA",
              "Destination": "TULA",
              "DestinationState": "MX",
              "LocationName": "Matehuala",
              "LocationState": "MX",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-08T04:35:22",
              "Duration": "00:00:00",
              "EtaDate": "2021-04-15T14:16:04",
              "EtaRailroadDate": "2021-04-11T06:00:00",
              "ArrivalStatus": "Late",
              "Latitude": 24.178749084473,
              "Longitude": -100.885971069336,
              "WaybillIdentifier": "1f958e1c-43db-44b0-9cff-0774aea0071d",
              "WaybillDestination": "TULA",
              "WaybillDestinationState": "HG",
              "TrainID": "",
              "ClmCode": "P",
              "ClmSightingDate": "2021-04-15T13:56:00",
              "ClmCodeDescription": "Departure",
              "CareOfParty": "FR TERMINALES SA DE CV",
              "RailRoad": "KCSM",
              "BOL": 72995287,
              "SID": "2928170",
              "Customer": "HUNTSMAN CORP",
              "CustPO": "3608",
              "Product": "RR",
              "NetWeight": 188554,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 662395",
              "AssetId": 93293,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "GEISMAR",
              "OriginState": "LA",
              "Destination": "KINARDS",
              "DestinationState": "SC",
              "LocationName": "Newberry",
              "LocationState": "SC",
             "TripStatus": "Enroute",
              "DepartureDate": "2021-04-07T21:00:41",
              "Duration": "3208.18:00:00",
              "EtaDate": "2021-04-15T15:01:04",
              "EtaRailroadDate": null,
              "ArrivalStatus": "-",
              "Latitude": 34.256565093994,
              "Longitude": -81.581512451172,
              "WaybillIdentifier": "a1757879-0e66-474d-96ca-f1eae46b48ed",
              "WaybillDestination": "KINARDS",
              "WaybillDestinationState": "SC",
              "TrainID": "",
              "ClmCode": "D",
              "ClmSightingDate": "2021-04-15T07:37:00",
              "ClmCodeDescription": "Arrival at Destination",
              "CareOfParty": "NORBORD SOUTH CAROLINA INC",
              "RailRoad": "CSXT",
              "BOL": 80866746,
              "SID": "2930033",
              "Customer": "HUNTSMAN POLYURETHANES INC.",
              "CustPO": "4570628714",
              "Product": "TN",
              "NetWeight": 188170,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 643254",
              "AssetId": 92217,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "GEISMAR",
              "OriginState": "LA",
              "Destination": "TACOMA",
              "DestinationState": "WA",
              "LocationName": "East Glacier Park",
              "LocationState": "MT",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-07T11:44:04",
              "Duration": "11268.21:30:00",
              "EtaDate": "2021-04-18T15:23:31.5",
              "EtaRailroadDate": "2021-04-22T11:00:00",
              "ArrivalStatus": "Late",
              "Latitude": 48.491218566895,
              "Longitude": -113.143692016602,
              "WaybillIdentifier": "af215d8f-89fc-46a0-94b4-9a8038b55da6",
              "WaybillDestination": "TACOMA",
              "WaybillDestinationState": "WA",
              "TrainID": "",
              "ClmCode": "P",
              "ClmSightingDate": "2021-04-15T14:30:00",
              "ClmCodeDescription": "Departure",
              "CareOfParty": "CARLISLE CONSTRUCTION MATERIALS INC",
              "RailRoad": "BNSF",
              "BOL": 72995865,
              "SID": "2929845",
              "Customer": "INTELLITRANS INC",
              "CustPO": "10455303",
              "Product": "TN",
              "NetWeight": 188564,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 665236",
              "AssetId": 92328,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "GEISMAR",
              "OriginState": "LA",
              "Destination": "TWO HARBORS",
              "DestinationState": "MN",
              "LocationName": "Iron Junction",
              "LocationState": "MN",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-07T08:36:58",
              "Duration": "3696.06:00:00",
              "EtaDate": "2021-04-15T18:14:23",
              "EtaRailroadDate": "2021-04-15T23:00:00",
              "ArrivalStatus": "Late",
              "Latitude": 47.393863677979,
              "Longitude": -92.622352600098,
              "WaybillIdentifier": "4404facf-858e-482b-8849-514b5923bd9a",
              "WaybillDestination": "TWO HARBORS",
              "WaybillDestinationState": "MN",
              "TrainID": "L56781",
              "ClmCode": "P",
              "ClmSightingDate": "2021-04-13T11:02:00",
              "ClmCodeDescription": "Departure",
              "CareOfParty": "LOUISIANA PACIFIC CORP",
              "RailRoad": "CN",
              "BOL": 80866885,
              "SID": "2930618",
              "Customer": "HUNTSMAN POLYURETHANES INC.",
              "CustPO": "4570629211",
              "Product": "TN",
              "NetWeight": 188060,
              "DefaultJsonData": null
          },
          {
              "Asset": "UTLX 683712",
              "AssetId": 102838,
              "AssetGroup": "MDI",
              "AssetGroupId": 1229,
              "LoadStatus": "Loaded",
              "Origin": "GEISMAR",
              "OriginState": "LA",
              "Destination": "HIGH LEVEL",
              "DestinationState": "AB",
              "LocationName": "High Level",
              "LocationState": "AB",
              "TripStatus": "Enroute",
              "DepartureDate": "2021-04-06T08:32:22",
              "Duration": "00:00:00",
              "EtaDate": "2021-04-15T13:40:58",
              "EtaRailroadDate": "2021-04-05T18:00:00",
              "ArrivalStatus": "Late",
              "Latitude": 58.446662902832,
              "Longitude": -117.206809997559,
              "WaybillIdentifier": "5fc052fc-d39a-4ef7-8e37-09623a1bcc9d",
              "WaybillDestination": "HIGH LEVEL",
              "WaybillDestinationState": "AB",
              "TrainID": "",
              "ClmCode": "Z",
              "ClmSightingDate": "2021-04-06T11:26:00",
              "ClmCodeDescription": "Actual Placement",
              "CareOfParty": "NORBORD INC.",
              "RailRoad": "CN",
              "BOL": 80866729,
              "SID": "2924314",
              "Customer": "HUNTSMAN POLYURETHANES INC.",
              "CustPO": "4570629384",
              "Product": "TN",
              "NetWeight": 187980,
              "DefaultJsonData": null
          },
      {
                "Asset": "ADSX 123456",
                "AssetId": 102838,
                "AssetGroup": "MDI",
                "AssetGroupId": 1229,
                "LoadStatus": "Loaded",
                "Origin": "GEISMAR",
                "OriginState": "LA",
                "Destination": "HIGH LEVEL",
                "DestinationState": "AB",
                "LocationName": "High Level",
                "LocationState": "AB",
                "TripStatus": "Enroute",
                "DepartureDate": "2021-04-06T08:32:22",
                "Duration": "00:00:00",
                "EtaDate": "2021-04-15T13:40:58",
                "EtaRailroadDate": "2021-04-05T18:00:00",
                "ArrivalStatus": "Late",
                "Latitude": 58.446662902832,
                "Longitude": -117.206809997559,
                "WaybillIdentifier": "5fc052fc-d39a-4ef7-8e37-09623a1bcc9d",
                "WaybillDestination": "HIGH LEVEL",
                "WaybillDestinationState": "AB",
                "TrainID": "",
                "ClmCode": "Z",
                "ClmSightingDate": "2021-04-06T11:26:00",
                "ClmCodeDescription": "Actual Placement",
                "CareOfParty": "NORBORD INC.",
                "RailRoad": "CN",
                "BOL": 80866729,
                "SID": "2924314",
                "Customer": "HUNTSMAN POLYURETHANES INC.",
                "CustPO": "4570629384",
                "Product": "TN",
                "NetWeight": 187980,
                "DefaultJsonData": null
            },
        {
                  "Asset": "HA0004434A",
                  "AssetId": 102838,
                  "AssetGroup": "MDI",
                  "AssetGroupId": 1229,
                  "LoadStatus": "Loaded",
                  "Origin": "GEISMAR",
                  "OriginState": "LA",
                  "Destination": "HIGH LEVEL",
                  "DestinationState": "AB",
                  "LocationName": "High Level",
                  "LocationState": "AB",
                  "TripStatus": "Enroute",
                  "DepartureDate": "2021-04-06T08:32:22",
                  "Duration": "00:00:00",
                  "EtaDate": "2021-04-15T13:40:58",
                  "EtaRailroadDate": "2021-04-05T18:00:00",
                  "ArrivalStatus": "Late",
                  "Latitude": 58.446662902832,
                  "Longitude": -117.206809997559,
                  "WaybillIdentifier": "5fc052fc-d39a-4ef7-8e37-09623a1bcc9d",
                  "WaybillDestination": "HIGH LEVEL",
                  "WaybillDestinationState": "AB",
                  "TrainID": "",
                  "ClmCode": "Z",
                  "ClmSightingDate": "2021-04-06T11:26:00",
                  "ClmCodeDescription": "Actual Placement",
                  "CareOfParty": "NORBORD INC.",
                  "RailRoad": "CN",
                  "BOL": 80866729,
                  "SID": "2924314",
                  "Customer": "HUNTSMAN POLYURETHANES INC.",
                  "CustPO": "4570629384",
                  "Product": "TN",
                  "NetWeight": 187980,
                  "DefaultJsonData": null
              },
          {
                    "Asset": "81 70 7829 0274",
                    "AssetId": 102838,
                    "AssetGroup": "MDI",
                    "AssetGroupId": 1229,
                    "LoadStatus": "Loaded",
                    "Origin": "GEISMAR",
                    "OriginState": "LA",
                    "Destination": "HIGH LEVEL",
                    "DestinationState": "AB",
                    "LocationName": "High Level",
                    "LocationState": "AB",
                    "TripStatus": "Enroute",
                    "DepartureDate": "2021-04-06T08:32:22",
                    "Duration": "00:00:00",
                    "EtaDate": "2021-04-15T13:40:58",
                    "EtaRailroadDate": "2021-04-05T18:00:00",
                    "ArrivalStatus": "Late",
                    "Latitude": 58.446662902832,
                    "Longitude": -117.206809997559,
                    "WaybillIdentifier": "5fc052fc-d39a-4ef7-8e37-09623a1bcc9d",
                    "WaybillDestination": "HIGH LEVEL",
                    "WaybillDestinationState": "AB",
                    "TrainID": "",
                    "ClmCode": "Z",
                    "ClmSightingDate": "2021-04-06T11:26:00",
                    "ClmCodeDescription": "Actual Placement",
                    "CareOfParty": "NORBORD INC.",
                    "RailRoad": "CN",
                    "BOL": 80866729,
                    "SID": "2924314",
                    "Customer": "HUNTSMAN POLYURETHANES INC.",
                    "CustPO": "4570629384",
                    "Product": "TN",
                    "NetWeight": 187980,
                    "DefaultJsonData": null
                }
      ];
      
    this.customersData = this.customers;
    this.columnDefs = [
      { headerName: 'Car/Wagon', field: 'Asset' , checkboxSelection: true, filter: 'carFilter'},
      { headerName: 'Fleet', field: 'AssetGroup', width: '80px', filter: 'agMultiColumnFilter',
      filterParams: {
        buttons: ['apply', 'reset'],
        filters: [
          {
            filter: 'agTextColumnFilter'
          },
          { filter: 'agSetColumnFilter' }
        ],
        filterOptions: ['equals', 'notEqual'],
    }},
      {  headerName: 'L/E', field: 'LoadStatus', filter: 'agMultiColumnFilter', filterParams: {
        filters: [{
          filter: 'agTextColumnFilter',
          filterOptions: ['equals', 'notEqual'],
        },{
          filter: 'agSetColumnFilter'
        }],
        
        buttons: ['apply', 'reset'],
        debounceMs: 200
      }},
      { headerName: 'Origin', field: 'Origin', width: '100px' },
      { headerName: 'O', field: 'OriginState', width: '130px' },
      { headerName: 'Destination', field: 'Destination', width: '100px'},
      { headerName: 'D', field: 'DestinationState', width: '150px' },
      { headerName: 'Departure', field: 'DepartureDate' },
      { headerName: 'ETA Predicted', field: 'EtaDate', width: '100px'},
      { headerName: 'Arrival Status', field: 'ArrivalStatus'},
      { headerName: 'Code', field: 'ClmCode', width: '100px'},
      { headerName: 'Code Description', field: 'ClmCodeDescription'},
      { headerName: 'BOL#', field: 'BOL', width: '100px'},
      { headerName: 'ETA Deviation (FUTURE)', field: 'ETADeviation'},
      { headerName: 'Currency (FUTURE)', field: 'Currency'}
    ];

    this.defaultColDef = {
      editable: false,
      sortable: true,
      flex: 1,
      minWidth: 200,
      filter: true,
      menuTabs: ['filterMenuTab'],
      resizable: true,
    };

    this.frameworkComponents = {
      carFilter: CarFilter
    };

    this.subscriptions = this.sharedService.searchSubject.subscribe(searchTextValue => {
        this.filterCarData(searchTextValue);
      });
  }

  filterCarData(data: any) {
    if(data){
      let filter: boolean = false;
      let filteredData: any[] = [];
      let doesNotExist: any[] = [];
      if(data && data.length) {
        for(let x=0; x<data.length; x++) {
          //filter = this.customers.filter(resp => (resp.Asset).toLowerCase() === data[x].carId.trim().toLowerCase());
          filter = false;
          this.customers.filter(resp => {
            if(resp.Asset.toLowerCase().indexOf(data[x].carId.trim().toLowerCase()) != -1){
              let exist = filteredData.filter(obj => obj.Asset === resp.Asset);
              filter = true;
              if(exist.length === 0){
                filteredData.push(resp);
              }
            }
          });

          if(!filter) {
            doesNotExist.push(data[x].carId);
          }
        }

        this.customersData = filteredData;
      } else {
        this.customersData = this.customers;
      }

      this.sharedService.searchDataNotExist.next(doesNotExist);
    }
  }

  onRowSelect(event: any) {
    let index = this.customers.findIndex((resp: any) => this.selectedCustomers.Asset === resp.Asset);
    let obj = {
      index: index,
      list: this.customers
    }
    this.sharedService.selectedCustomer.next(obj);
  }

  getSelectedRows() {
    const selectedNodes = this.agGrid.api.getSelectedNodes();
    const selectedData = selectedNodes.map(node => node.data );
    const selectedDataStringPresentation = selectedData.map(node => `${node.name}`).join(', ');

    alert(`Selected nodes: ${selectedDataStringPresentation}`);
  }

  onRowSelected(obj: any) {
    if(!obj.node.selected) {
      obj.node.gridApi.focusController.clearFocusedCell()
    }
  }

  ngOnDestroy() {
    this.subscriptions.unsubscribe();
  }

}
